export const Permissions = {
  Admissions: {
    ViewApplications:   'Admissions.ViewApplications',
    EditApplications:   'Admissions.EditApplications',
    ViewEnquiries:      'Admissions.ViewEnquiries',
    EditEnquiries:      'Admissions.EditEnquiries',
    ViewInterviews:     'Admissions.ViewInterviews',
    EditInterviews:     'Admissions.EditInterviews',
  },
  Agencies: {
    ViewAgencies: 'Agencies.ViewAgencies',
    EditAgencies: 'Agencies.EditAgencies',
  },
  Assessment: {
    ViewAspects:            'Assessment.ViewAspects',
    EditAspects:            'Assessment.EditAspects',
    ViewExamBaseData:       'Assessment.ViewExamBaseData',
    EditExamBaseData:       'Assessment.EditExamBaseData',
    RunExamAsst:            'Assessment.RunExamAsst',
    ViewGradeSets:          'Assessment.ViewGradeSets',
    EditGradeSets:          'Assessment.EditGradeSets',
    ViewMarksheetTemplates: 'Assessment.ViewMarksheetTemplates',
    EditMarksheetTemplates: 'Assessment.EditMarksheetTemplates',
    ViewResultSets:         'Assessment.ViewResultSets',
    EditResultSets:         'Assessment.EditResultSets',
    ViewOwnMarksheets:      'Assessment.ViewOwnMarksheets',
    ViewAllMarksheets:      'Assessment.ViewAllMarksheets',
    UpdateOwnMarksheets:    'Assessment.UpdateOwnMarksheets',
    UpdateAllMarksheets:    'Assessment.UpdateAllMarksheets',
    ViewResults:            'Assessment.ViewResults',
    ViewEmbargoedResults:   'Assessment.ViewEmbargoedResults',
    EditResults:            'Assessment.EditResults',
  },
  Attendance: {
    ViewAttendanceMarks: 'Attendance.ViewAttendanceMarks',
    EditAttendanceMarks: 'Attendance.EditAttendanceMarks',
    UseRestrictedCodes:  'Attendance.UseRestrictedCodes',
  },
  Behaviour: {
    ViewAchievements:     'Behaviour.ViewAchievements',
    EditAchievements:     'Behaviour.EditAchievements',
    ViewIncidents:        'Behaviour.ViewIncidents',
    EditIncidents:        'Behaviour.EditIncidents',
    ViewDetentions:       'Behaviour.ViewDetentions',
    EditDetentions:       'Behaviour.EditDetentions',
    ViewExclusions:       'Behaviour.ViewExclusions',
    EditExclusions:       'Behaviour.EditExclusions',
    ViewReportCards:      'Behaviour.ViewReportCards',
    EditReportCards:      'Behaviour.EditReportCards',
    AddRemoveReportCards: 'Behaviour.AddRemoveReportCards',
  },
  Curriculum: {
    AcademicStructure: 'Curriculum.AcademicStructure',
    EditAcademicYears: 'Curriculum.EditAcademicYears',
    ArrangeCover:      'Curriculum.ArrangeCover',
    ViewHomework:      'Curriculum.ViewHomework',
    EditHomework:      'Curriculum.EditHomework',
    ViewLessonPlans:   'Curriculum.ViewLessonPlans',
    EditLessonPlans:   'Curriculum.EditLessonPlans',
    ViewStudyTopics:   'Curriculum.ViewStudyTopics',
    EditStudyTopics:   'Curriculum.EditStudyTopics',
  },
  Finance: {
    ViewAccounts:  'Finance.ViewAccounts',
    EditAccounts:  'Finance.EditAccounts',
    ViewProducts:  'Finance.ViewProducts',
    EditProducts:  'Finance.EditProducts',
    ViewBills:     'Finance.ViewBills',
    EditBills:     'Finance.EditBills',
    ViewCharges:   'Finance.ViewCharges',
    EditCharges:   'Finance.EditCharges',
    ViewDiscounts: 'Finance.ViewDiscounts',
    EditDiscounts: 'Finance.EditDiscounts',
  },
  People: {
    ViewAgentDetails:   'People.ViewAgentDetails',
    EditAgentDetails:   'People.EditAgentDetails',
    ViewContactDetails: 'People.ViewContactDetails',
    EditContactDetails: 'People.EditContactDetails',
    ViewContactTasks:   'People.ViewContactTasks',
    EditContactTasks:   'People.EditContactTasks',
  },
  Profiles: {
    ViewCommentBanks:      'Profiles.ViewCommentBanks',
    EditCommentBanks:      'Profiles.EditCommentBanks',
    ViewReports:           'Profiles.ViewReports',
    EditOwnReports:        'Profiles.EditOwnReports',
    EditAllReports:        'Profiles.EditAllReports',
    ViewReportingSessions: 'Profiles.ViewReportingSessions',
    EditReportingSessions: 'Profiles.EditReportingSessions',
  },
  School: {
    PastoralStructure:      'School.PastoralStructure',
    ViewRooms:              'School.ViewRooms',
    EditRooms:              'School.EditRooms',
    ViewSchoolDetails:      'School.ViewSchoolDetails',
    EditSchoolDetails:      'School.EditSchoolDetails',
    ViewSchoolDiary:        'School.ViewSchoolDiary',
    EditSchoolDiary:        'School.EditSchoolDiary',
    ViewSchoolDocuments:    'School.ViewSchoolDocuments',
    EditSchoolDocuments:    'School.EditSchoolDocuments',
    ViewSchoolBulletins:    'School.ViewSchoolBulletins',
    EditSchoolBulletins:    'School.EditSchoolBulletins',
    ApproveSchoolBulletins: 'School.ApproveSchoolBulletins',
  },
  Student: {
    ViewSenDetails:       'Student.ViewSenDetails',
    EditSenDetails:       'Student.EditSenDetails',
    ViewStudentDetails:   'Student.ViewStudentDetails',
    EditStudentDetails:   'Student.EditStudentDetails',
    ViewStudentLogNotes:  'Student.ViewStudentLogNotes',
    EditStudentLogNotes:  'Student.EditStudentLogNotes',
    ViewStudentTasks:     'Student.ViewStudentTasks',
    EditStudentTasks:     'Student.EditStudentTasks',
    ViewStudentDocuments: 'Student.ViewStudentDocuments',
    EditStudentDocuments: 'Student.EditStudentDocuments',
    ViewMedicalEvents:    'Student.ViewMedicalEvents',
    EditMedicalEvents:    'Student.EditMedicalEvents',
    ViewFinanceDetails:   'Student.ViewFinanceDetails',
    EditFinanceDetails:   'Student.EditFinanceDetails',
  },
  Staff: {
    ViewStaffBasicDetails:              'Staff.ViewStaffBasicDetails',
    ViewStaffEmploymentDetails:         'Staff.ViewStaffEmploymentDetails',
    EditStaffBasicDetails:              'Staff.EditStaffBasicDetails',
    EditStaffEmploymentDetails:         'Staff.EditStaffEmploymentDetails',
    ViewAllStaffDocuments:              'Staff.ViewAllStaffDocuments',
    ViewManagedStaffDocuments:          'Staff.ViewManagedStaffDocuments',
    ViewOwnStaffDocuments:              'Staff.ViewOwnStaffDocuments',
    EditAllStaffDocuments:              'Staff.EditAllStaffDocuments',
    EditManagedStaffDocuments:          'Staff.EditManagedStaffDocuments',
    EditOwnStaffDocuments:              'Staff.EditOwnStaffDocuments',
    ViewAllStaffPerformanceDetails:     'Staff.ViewAllStaffPerformanceDetails',
    ViewManagedStaffPerformanceDetails: 'Staff.ViewManagedStaffPerformanceDetails',
    ViewOwnStaffPerformanceDetails:     'Staff.ViewOwnStaffPerformanceDetails',
    EditAllStaffPerformanceDetails:     'Staff.EditAllStaffPerformanceDetails',
    EditManagedStaffPerformanceDetails: 'Staff.EditManagedStaffPerformanceDetails',
    EditOwnStaffPerformanceDetails:     'Staff.EditOwnStaffPerformanceDetails',
    ViewAllStaffTasks:                  'Staff.ViewAllStaffTasks',
    ViewManagedStaffTasks:              'Staff.ViewManagedStaffTasks',
    EditAllStaffTasks:                  'Staff.EditAllStaffTasks',
    EditManagedStaffTasks:              'Staff.EditManagedStaffTasks',
    ViewTrainingCourses:                'Staff.ViewTrainingCourses',
    EditTrainingCourses:                'Staff.EditTrainingCourses',
  },
  System: {
    ViewUsers:           'System.ViewUsers',
    EditUsers:           'System.EditUsers',
    ViewGroups:          'System.ViewGroups',
    EditGroups:          'System.EditGroups',
    Settings:            'System.Settings',
    AttendanceSettings:  'System.AttendanceSettings',
    BehaviourSettings:   'System.BehaviourSettings',
    FinanceSettings:     'System.FinanceSettings',
    PersonSettings:      'System.PersonSettings',
    StaffSettings:       'System.StaffSettings',
    SenSettings:         'System.SenSettings',
  }
} as const;

// Flatten to a union type of all permission strings
type Category = typeof Permissions[keyof typeof Permissions];
export type Permission = Category[keyof Category];

// Convenience: a flat readonly array if you ever need it
export const ALL_PERMISSIONS = Object.freeze(
  Object.values(Permissions).flatMap(cat => Object.values(cat))
) as readonly Permission[];
